language: python
dist: trusty
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install .[dev]
  - pip install pytest pytest-cov coverage
script:
  - py.test --cov=csb --cov-report term csb/test/cases
